[env]
OPENAI_API_KEY="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"
LANGCHAIN_API_KEY="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"
LANGCHAIN_PROJECT="Prima Power RAG Demo"
GROQ_API_KEY="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"
HUGGINGFACEHUB_API_TOKEN="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"
COHERE_API_KEY="nNUnNhpdYSblV5aOSCveKrNjIVpFpC5mf1ilDIzm"
