[env]
OPENAI_API_KEY="sk-XpYwOmNTslHEfsWzIhmGK135wIKIJ-rElL6f0Fwx38T3BlbkFJjwEX4Q793YWMP9j5Id9nK_MMWRrdHYgz_fOZQwLPMA"
LANGCHAIN_API_KEY="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"
LANGCHAIN_PROJECT="Prima Power Demo"
GROQ_API_KEY="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"
HUGGINGFACEHUB_API_TOKEN="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"
COHERE_API_KEY="nNUnNhpdYSblV5aOSCveKrNjIVpFpC5mf1ilDIzm"
