[env]
OPENAI_API_KEY="sk-SGfnwuvYgsJXc74V_LpWiebz5sMCGmcveKUaieQ2mjT3BlbkFJkzGi9ki5b6HJXDkmNQMqffcgzJYbHMlVxYIwYGtwAA"
LANGCHAIN_API_KEY="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"
LANGCHAIN_PROJECT="Prima Power Demo"
GROQ_API_KEY="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"
HUGGINGFACEHUB_API_TOKEN="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"
COHERE_API_KEY="nNUnNhpdYSblV5aOSCveKrNjIVpFpC5mf1ilDIzm"
