[env]
OPENAI_API_KEY="sk-aZlE8F364c5sVw1vcpl8Rmd7eNLSfOT0Sm78zXIIftT3BlbkFJ6sZFvEwP4oe-CyWSrPjty8onTVPxFh-8NeIvllVvQA"
LANGCHAIN_API_KEY="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"
LANGCHAIN_PROJECT="Prima Power Demo"
GROQ_API_KEY="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"
HUGGINGFACEHUB_API_TOKEN="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"
COHERE_API_KEY="nNUnNhpdYSblV5aOSCveKrNjIVpFpC5mf1ilDIzm"
