wandb_version: 1

hugging_face_token:
  desc: null
  value: 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
groq_api_key:
  desc: null
  value: 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
framework:
  desc: null
  value: few_shot_learning
project:
  desc: null
  value: few_shot
test_dataset:
  desc: null
  value: /Users/hadiibrahim/Dev/prima-power-hmi-assistant/src/data/testset_manual.csv
train_dataset:
  desc: null
  value: /Users/hadiibrahim/Dev/prima-power-hmi-assistant/src/data/trainset_manual.csv
exp_name:
  desc: null
  value: few_shot_t0_k2
phase:
  desc: null
  value: all
not_use_local_logging:
  desc: null
  value: false
not_use_wandb:
  desc: null
  value: false
seed:
  desc: null
  value: 516
epoch:
  desc: null
  value: 20
train_batch_size:
  desc: null
  value: 20
val_batch_size:
  desc: null
  value: 4
test_batch_size:
  desc: null
  value: 1
model_name:
  desc: null
  value: llama3-70b-8192
temperature:
  desc: null
  value: 0.0
k:
  desc: null
  value: 2
is_llm:
  desc: null
  value: false
answers_folder:
  desc: null
  value: null
load_checkpoint:
  desc: null
  value: false
model_checkpoint:
  desc: null
  value: ./new_weights_comet/final_Trial1_context_comet
test_output_file_name:
  desc: null
  value: results.json
_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.41.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717858138
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 100
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 86
      - 100
      - 105
      3:
      - 2
      - 13
      - 16
      - 23
      - 62
      4: 3.11.9
      5: 0.17.0
      6: 4.41.1
      8:
      - 5
      13: darwin-x86_64
